### ISSUE TITLE
ERROR  Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: none)

### ISSUE THREAD

**Issue by GreatHK** [NVIDIA/cuda-python#34]
venv "C:\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 227, in <module>
    prepare_enviroment()
  File "C:\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 150, in prepare_enviroment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "C:\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 33, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113

stderr: ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1+cu113

Press any key to continue . . .

**Comment by jakirkham** [comment]
Would suggest [filing an issue with PyTorch including all relevant details]( https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&template=bug-report.yml )
